 final List<String> animals = [
    "images/dogs/1.png",
    "images/dogs/2.png",
    "images/dogs/3.png",
    "images/dogs/4.png",
    "images/dogs/5.png",
    "images/dogs/6.png",
    "images/dogs/7.png",
    "images/dogs/8.png",
    "images/dogs/9.png",
    "images/dogs/10.png",
    "images/dogs/11.png",
    "images/dogs/12.png",
    "images/dogs/13.png",
  ];